### ISSUE TITLE
Unreadable foreground text in balloons

### ISSUE THREAD

**Issue by gayanper** [arcticicestudio/nord-jetbrains#102] opened 2019-09-25 05:05 UTC
![image](https://user-images.githubusercontent.com/7471994/65570820-038eaa00-df80-11e9-8f7c-d31b1b1e9bf0.png)

In structural search window this foreground text in unreadable. May be we could have a balloon color which will match both dark and light foreground colors. Because most of the time the foreground color is either black or white in plugins.

**Comment by arcticicestudio** [comment] 2019-09-25 10:49
Duplicates #59 

---

Hi @gayanper :wave:, thanks for your contribution :+1:
This is a duplicate of #59, but like explained in [in this comment][c] there's currently no way for theme authors to customize these elements. Please subscribe to #59 to get notified about possible solutions like updates to JetBrains theme API.

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/59#issuecomment-502009682

**Closed by arcticicestudio** 2019-09-25 10:49 UTC
Labels: context-ui, resolution-duplicate, scope-ux
