### ISSUE TITLE
Code competition window background

### ISSUE THREAD

**Issue by alekc** [arcticicestudio/nord-jetbrains#88] opened 2019-08-02 22:43 UTC
There is a weird bug triggered on intellisense on
GoLand 2019.2
Build #GO-192.5728.103, built on July 23, 2019

![](https://i.imgur.com/HT505h1.png)

Basically code competition window (which appears while you are writing code), is ileggible until you press some key (i.e. move with arrows up or down). Issues is not triggered if I press ctrl space and call for intellisense in explicit manner.

**Comment by arcticicestudio** [comment] 2019-08-03 06:39
Hi @alekc :wave: , thanks for your report :+1:

1. Please post the name and version of your operating system.
2. Is the problem reproducible with other (official) themes like _Darcula_ or _IntelliJ_ (_Default_)?
If yes this bug should be reported to YouTrack.
I've quickly checked the latest reports, but only found a problem regarding [text that gets cut off in the popup][rider-31013] for the Rider IDE and multiple performance problems (that are marked as critical/„show stopper“) regarding [high CPU usage for IntelliSense][rsrp-474835].
3. What's the version of the Nord plugin you're using? If it's not the latest version [v0.8.0][] please update since this version includes explicit support for the latest JetBrains 2019.2 products.
4. If you're using the latest Nord plugin version could and the problem still exists, could you please try to delete the [`colors` directory in Goland's configuration directory][cdoc]? The folder only might contain a copy of the Nord theme when you've ever modified any part of the UI/editor color scheme so this might conflict with the plugin leading to compatibility problems.

[rider-31013]: https://youtrack.jetbrains.com/issue/RIDER-31013
[rsrp-474835]: https://youtrack.jetbrains.com/issue/RSRP-474835
[v0.8.0]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.0
[cdoc]: https://www.jetbrains.com/help/idea/tuning-the-ide.html#default-dirs

**Comment by arcticicestudio** [comment] 2019-08-03 06:50
I've been able to reproduce the problem using IntelliJ and GoLand. All items are "invisible" until the up or down arrow button has been pressed to navigate through the list. I'll need to check if any UI theme key is the root cause or theme API v2019.2 introduced any new key the theme currently misses. Otherwise I'll create a report in JetBrains bug tracker so this can be analysed as soon as possible.

**Comment by arcticicestudio** [comment] 2019-08-03 06:55
Also I currently don't know if this is related to the problem or the already known performance problems mentioned in the YouTrack tickets linked above, but the whole IDE seems to be way slower than any version of 2019.1. Maybe the list in the popup is not loaded correctly due to internal errors.

**Comment by arcticicestudio** [comment] 2019-08-03 08:03
The official bundled themes are working fine, so the problem is definitely scoped to Nord only.

<p align="center">Darcula</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62409349-f4b9f580-b5d5-11e9-8369-97c6a9957550.gif" /></p>

<p align="center">IntelliJ/Light (Default)</p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/62409350-f4b9f580-b5d5-11e9-92ad-329e7f95081a.gif" /></p>

**Comment by arcticicestudio** [comment] 2019-08-03 08:21
It looks like the JetBrains 2019.2 products are currently all affected by performance problems. My IntelliJ Ultimate Edition 2019.2 closed with out of memory some moments ago for the first time (16GB RAM, IntelliJ is configured to use to use ~6GB). It completely polluted my system with log and dump files taking more than 12GB. It's not possible to debug the theme at the moment.

I'll try [some known workarounds][ref] as well as switching the boot JRE of IntelliJ to a JetBrains specific JRE:

```properties
-XX:TieredStopAtLevel=1
-XX:CICompilerCount=2
-XX:Tier4MinInvocationThreshold=100000
-XX:Tier4InvocationThreshold=110000
-XX:Tier4CompileThreshold=120000
```

[ref]: See https://youtrack.jetbrains.com/issue/IDEA-207243#focus=streamItem-27-3529598.0-0

**Comment by arcticicestudio** [comment] 2019-08-03 08:57
I've identified the root cause: In [v0.8.0][] some new UI theme keys have been added and deprecated ones modified or removed. This includes the `ui.CompletionPopup.nonFocusedMask` key that has been set to `nord0` without a alpha layer value. Since the auto completion popup of IntelliSense if not focused but the editor itself, the overlay mask gets applied. As soon as the up or down arrow keys are pressed the popup gets the focus and therefore the mask gets removed showing the list items with correct styles.

The key will be removed, the popup should be shown the same like in focused state for better readable text and easy recognition of the desired auto complete entry. The filx will be released as new bugfix plugin version [0.8.1][].

[0.8.1]: https://github.com/arcticicestudio/nord-jetbrains/projects/12

**Closed** 2019-08-03 09:17 UTC
Labels: context-ui, scope-compatibility, scope-ux, status-accepted, status-pending, type-bug

**Comment by arcticicestudio** [comment] 2019-08-03 09:34
The fix has been merged in #89 and release version [0.8.1][] published and deployed to the JetBrains marketplace. As soon as the new plugin version passes the JetBrains validation process the update will be available through the IDE plugin auto-update.

[0.8.1]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.1

**Comment by wendzhue** [comment] 2019-08-03 13:50
Great! I came across this problem today and it got fixed so quick!

**Comment by dallbee** [comment] 2019-08-04 16:48
Just noticed this today, thanks for fixing it so fast!
