### ISSUE TITLE
Illegible background on build/run config in GoLand

### ISSUE THREAD

**Issue by alekc** [arcticicestudio/nord-jetbrains#96] opened 2019-08-16 13:50 UTC
![image](https://user-images.githubusercontent.com/302807/63172147-ef789400-c034-11e9-9828-0dce8e320be6.png)

This happens if `.gitignore` file contains 
```
/.idea
``` 
and in run/debug configuration you check the box "Share through vcs"

Windows 10, Goland 2019.2

**Comment by arcticicestudio** [comment] 2019-08-17 05:38
Hi @alekc :wave:, thanks for your contribution :+1:
This is related to #59 and there as far as I know the current theme API provides no way to allow theme authors to control the background and foreground color of such popups. These components use the make use of the _warning_ color defined by the theme, but doesn't allow to specify how it should be used. In https://github.com/arcticicestudio/nord-jetbrains/issues/59#issuecomment-502009682 I reproduced the problem and still need to create an issue in _YouTrack_ so this can be improved by JetBrains.
Please subscribe to #59 in order to get updates about the status.

Duplicate of #59

**Closed by arcticicestudio** 2019-08-17 05:38 UTC
