### ISSUE TITLE
Color inconsistency in debug view

### ISSUE THREAD

**Issue by gayanper** [arcticicestudio/nord-jetbrains#98] opened 2019-08-21 09:36 UTC
![image](https://user-images.githubusercontent.com/7471994/63420899-47dcd680-c425-11e9-9ccd-c383f63e5588.png)

Background color of the stack entries are in consistent, it has the same background color as Dracula theme.

**Comment by arcticicestudio** [comment] 2019-08-21 13:10
Hi @gayanper, this is the same problem described in #67, [please see my comment][c] and the follow-up conversation that provides information about the problem and how to solve it on your side. As a theme author there is actually no way to fix this and it must be resolved within the JetBrains theme API itself.

---

Duplicate of #67 

[c]: https://github.com/arcticicestudio/nord-jetbrains/issues/67#issuecomment-511395276

**Closed by arcticicestudio** 2019-08-21 13:10 UTC
