### ISSUE TITLE
Text in Excluded folders are almost invisible until you select it 

### ISSUE THREAD

**Issue by bmarvinb** [arcticicestudio/nord-jetbrains#198] opened 2022-06-17 08:12 UTC
<img width="497" alt="CleanShot 2022-06-17 at 11 11 16@2x" src="https://user-images.githubusercontent.com/23120972/174256379-6afdef91-9528-4f4c-a17e-5cdfb12e639d.png">

Here is how it's look like

**Comment by svengreb** [comment] 2022-06-17 19:34
Duplicate of #57

---

Hi @bmarvinb :wave:, thanks for your contribution :+1:
This is a known problem tracked in the pinned issue #57. Please see [my comment that describes the current limitation for theme authors][1] as well as comments from other users like the ones that describes [how to fix it on your side][2].

[1]: https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-517267937
[2]: https://github.com/arcticicestudio/nord-jetbrains/issues/57#issuecomment-549154675

**Closed by svengreb** 2022-06-17 19:34 UTC
