### ISSUE TITLE
Could not found which break point is is encounter when debugging

### ISSUE THREAD

**Issue by haolly** [arcticicestudio/nord-jetbrains#177] opened 2021-09-08 08:50 UTC
![image](https://user-images.githubusercontent.com/2383231/132477725-2fa4ee9f-29ba-4fb5-8ae1-3b2ac5a122d8.png)

If a file has multiple break, when there is a break point encounterd when debugging, you could not found which break point line is

**Comment by piotrekfus91** [comment] 2021-12-30 14:43
Same for me, is there any chance to distinguish active breakpoint?

**Comment by arcticicestudio** [comment] 2022-01-30 09:33
Hi @haolly :wave:, thanks for your contribution :+1:
The problem has already been reported in #162 and there are plans to refactor the current line styles for the debug mode and general selections in the editor.

**Comment by svengreb** [comment] 2022-06-17 19:38
Duplicate of #162

---

@haolly @austinmcconnell @piotrekfus91 Thanks for your patience, there are tons of tasks in the Nord project and my free time is limited to work on the massive amount of issues/PRs.
Anyway, I close this issue in favor of #162 so please subscribe to this issue for further updates and discussions.

**Closed by svengreb** 2022-06-17 19:38 UTC
Labels: status-tracking
