### ISSUE TITLE
Strange look when breakpoint enabled

### ISSUE THREAD

**Issue by bmarvinb** [arcticicestudio/nord-jetbrains#199] opened 2022-06-17 10:30 UTC
<img width="486" alt="CleanShot 2022-06-17 at 13 29 44@2x" src="https://user-images.githubusercontent.com/23120972/174281136-70216776-64c8-48d2-9f46-275c17a1f942.png">

I think It's not a proper solution, doesn't look great

**Comment by svengreb** [comment] 2022-06-17 19:36
Duplicate of #162

---

Hi @bmarvinb :wave:, thanks for your contribution :+1:
This is a known problem tracked in issue #162 and #55. Please see [my comment about the plans to refactor the current line styles for the debug mode and general selections in the editor][1] an subscribe to the issue for further updates and discussions.

[1]: https://github.com/arcticicestudio/nord-jetbrains/issues/162#issuecomment-1059730712

**Closed by svengreb** 2022-06-17 19:36 UTC
