### ISSUE TITLE
Test folder showing with background highlighted and hard to read

### ISSUE THREAD

**Issue by axelitus** [arcticicestudio/nord-jetbrains#47] opened 2019-04-23 18:26 UTC
On the new 0.5.0 UI theme using PhpStorm 2019.1 the tests folder is background-highlighted instead just coloring the folder icon. Moreover, the text color is hard to read due to contrast:
![image](https://user-images.githubusercontent.com/732441/56605326-82df1280-65c9-11e9-89f5-22b7c0a6975b.png)

Also, the selected folder caret is hard to see because of contrast again.

My suggestion is to make the caret the same color as the text for selected items:
![image](https://user-images.githubusercontent.com/732441/56606200-53310a00-65cb-11e9-8660-f55b35a0bfd3.png)

**Comment by axelitus** [comment] 2019-04-24 18:11
Also, the context menu when hitting `Alt+Enter > Import class` is hard to read, though the autocomplete window shows correctly:
![image](https://user-images.githubusercontent.com/732441/56683084-7a064380-6692-11e9-828e-b6c98e94c933.png)

![image](https://user-images.githubusercontent.com/732441/56683106-84c0d880-6692-11e9-8938-fd341166eee5.png)

**Comment by arcticicestudio** [comment] 2019-04-24 19:23
Thanks for the report :+1: 

These are some of the theme keys that are defined by the plugin theme scheme that I tried to figure out where they are used, but wasn't able to find all UI elements. I've added all currently unused keys in #45 so this might be one use case :smile: 
I'll take a look into it.

**Comment by arcticicestudio** [comment] 2019-04-25 05:36
I've tried to reproduce the problem (with IntelliJ IDEA 2019.1 Ultimate Edition), but it works fine there.
The only UI keys that use `nord13` and could cause this problem are

```json
"Component": {
  "inactiveWarningFocusColor": "#ebcb8b",
  "warningFocusColor": "#ebcb8b"
}
```

There are also these two keys, but they should only affect notifications: 

```json
"Notification": {
  "ToolWindow": {
    "warningBackground": "#ebcb8b",
    "warningBorderColor": "#ebcb8b",
  }
}
```

Also the background color for the `ValidationTooltip` scope should not affect the class import popup.
Could you please try to modify the both `Component` scoped keys and see if this fixes the problem?

Regarding the background color of the test folder can you please make sure you haven't set a custom color for it through **Settings** ➜ **Appearance & Behavior** ➜ **File Colors**.

I've never used PHP at all so I'd need to install a trial version of PhpStorm to test this, but it might be faster if you could test these both changes :smile:

**Comment by axelitus** [comment] 2019-04-25 12:50
Alright, the first issue is fixed. Indeed it was because of **Settings ➜ Appearance & Behavior ➜ File Colors**. I have disabled it now. (Screenshots show this behavior and it also happens with IntelliJ).

File Colors enabled:
![image](https://user-images.githubusercontent.com/732441/56736751-92c43700-672e-11e9-91ed-5aefd1ccaff7.png)

File Colors disabled:
![image](https://user-images.githubusercontent.com/732441/56736794-acfe1500-672e-11e9-8f93-a5035e125c39.png)

Those settings are set by default (I've never changed them at all...)

I'll now look into the `Alt+Enter` context menu, probably it has been fixed too with this.

**Comment by axelitus** [comment] 2019-04-25 12:59
All right. It hadn't been fixed but I know why now:

I have to uncheck all 3 checks in File Colors:
[ ] Enable File colors       (this affects the file tree view)
[ ] Use in Editor Tabs      (this affects the file tabs, screenshot below)
[ ] Use in Project View    (this affects the class import context menu)

Screenshot of tabs with **Use in Editor Tabs** enabled:
![image](https://user-images.githubusercontent.com/732441/56737276-af14a380-672f-11e9-84e3-2dbace16fc55.png)

Screenshot of tabs with **Use in Editor Tabs** enabled:
![image](https://user-images.githubusercontent.com/732441/56737306-c358a080-672f-11e9-83ce-b88c69219059.png)

Screenshot of class to import context menu with **Use in Project View** enabled:
![image](https://user-images.githubusercontent.com/732441/56737362-e6835000-672f-11e9-9d3e-3d5b87b9f556.png)

Screenshot of class to import context menu with **Use in Project View** disabled:
![image](https://user-images.githubusercontent.com/732441/56737455-10d50d80-6730-11e9-880e-6d85d2d38435.png)

**Comment by axelitus** [comment] 2019-04-25 13:19
I don't know if it's possible to provide custom colors for the file colors, but I tried out changing them to a light green shaded color for the tests and it looks good to me. It just gives a slight hint of a test block. I'm using `#363C48` as a custom color:
![image](https://user-images.githubusercontent.com/732441/56738597-9063dc00-6732-11e9-980c-1fc0e30da02f.png)

The other menu is trickier because of the _disabled_ text color, though I think the menu looks better without colors.

**Comment by axelitus** [comment] 2019-04-25 13:28
Finally, I ended up with this configuration:
![image](https://user-images.githubusercontent.com/732441/56739375-1af90b00-6734-11e9-8464-35d404a677ff.png)

With test color set to `#363C48`

**Comment by arcticicestudio** [comment] 2019-04-25 13:51
Thanks for the detailed tests.

The colors are defined through the `FileColor` key, but these are only color suggestions and users can change it to whatever they like.

```json
"FileColor": {
  "Blue": "#88c0d0",
  "Green": "#a3be8c",
  "Orange": "#d08770",
  "Rose": "#bf616a",
  "Violet": "#b48ead",
  "Yellow": "#ebcb8b"
}
```

I'd like to keep the current color since they are the base colors of the Nord palettes, but I'll open up a request in the JetBrain bugtracker to improve the theming support by allowing themes to change the foreground color. This way `nord0` could be used forthe font which makes the text readable again.

Using a color with a opacity less than 100% will currently bug the hell out of the IDE. I've tried to use it for contrast in panels and popup menus, but ended up in calculating the HEX value because the IDE had visual glitches like duplicated text, streak lines on scroll and randomly changed the color of various elements.

I guess we can close this issue for now and I'll add some infos in the trouble shooting guide for the theme when users facing this kind of style depending on their settings.

**Comment by axelitus** [comment] 2019-04-25 14:14
Yeah, my thoughts exactly from reading the Nord docs. Introducing a specific shade is not the way to go according to them, as the palette is to be kept narrowed to 15 colors.

Hopefully, JetBrains improves the customization and maybe in the future a properly supports opacity through HEXA values.

Thanks for the hard work!

**Comment by axelitus** [comment] 2019-05-01 17:01
I found another place where it is not readable:

![image](https://user-images.githubusercontent.com/732441/57029941-c8728f80-6c08-11e9-9665-33e4157baee5.png)

It's the debugging window, but I had it always in the _Console_ tab, this is the _Debugger_ tab.

**Comment by arcticicestudio** [comment] 2019-05-23 07:18
Looks like the _File Color_ definitions are used by some other UI elements around the IDE, so I've thought again about these colors and planned to remove them until JetBrains updates the theme API, but I've tested them with opacity and it seems like the buggy rendering with transparent colors is not triggered by these colors. So the next version will include changes for _File Colors_, reducing their opacity to 10% which is still enough to be recognizable, but should not destroy the readability of labels and appear too bright for most UI elements.

**Closed** 2019-05-23 08:45 UTC
Labels: context-ui-support, scope-ux, status-blocked, type-improvement

**Comment by axelitus** [comment] 2019-05-24 22:01
The new colors in the [0.6.0](https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.6.0) release look great!

![image](https://user-images.githubusercontent.com/732441/58358626-5d059180-7e45-11e9-95ac-bbe2fead2a8f.png)

![image](https://user-images.githubusercontent.com/732441/58358700-9fc76980-7e45-11e9-93a9-4c9a1b7bf0dd.png)

**Comment by arcticicestudio** [comment] 2019-05-25 05:49
Thanks, and in the end they are just quick suggestions and everyone can change them to whatever they like through the <kbd>Custom</kbd> color button in the _File Colors_ settings 😄
