### ISSUE TITLE
First render of auto completion menu is unreadable

### ISSUE THREAD

**Issue by rafaelrinaldi** [arcticicestudio/nord-jetbrains#93] opened 2019-08-07 17:46 UTC
First of all, thank you for this beautiful editor theme! It's very complete and I like it very much 👍 

For some reason since the last update the first render of the auto completion menu is unreadable to me. I have to hit one of the arrow keys at least once so I can be able to read the text.

![autocompletion](https://user-images.githubusercontent.com/87162/62645171-abd9a800-b919-11e9-9e9e-1fd6c58fce3d.gif)

If I switch to any other theme, this issue does not happen.

**Comment by arcticicestudio** [comment] 2019-08-07 18:04
Duplicate of #88 

---

Hi @rafaelrinaldi :wave:, thanks for your report :+1:
This was a known problem reported in #88 that was fixed in #89 an has been merged in to the already deployed release version [0.8.1][] some days ago. The plugin update is available from the JetBrains marketplace, but it was pending some days due to the weekend and JetBrains process to validate plugin updates manually (quality control, prevention of malicious plugins etc.).
You can update to the latest version from within PHPStorm using the [builtin plugin marketplace UI][m].

[0.8.1]: https://github.com/arcticicestudio/nord-jetbrains/releases/tag/v0.8.1
[m]: https://www.jetbrains.com/help/idea/managing-plugins.html#de4e8f8c

**Closed by arcticicestudio** 2019-08-07 18:04 UTC
